### ISSUE TITLE
Update deprecated code since iOS 10

### ISSUE THREAD

**Issue by joamafer** [blueshift-labs/Blueshift-iOS-SDK#56]
Currently the pod is returning several warnings due to syntax deprecated since iOS 10. Please could you release a new version with this fixed? Thanks

> 'UIMutableUserNotificationCategory' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNNotificationCategory
> 
> 'UIUserNotificationType' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNAuthorizationOptions
> 
> 'UILocalNotification' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNNotificationRequest

**Comment by aswani521** [comment]
Hey Jose Antonio, thanks for reporting the issue, we will look into this.
-Aswani

**Comment by joamafer** [comment]
Thanks @aswani521 do you have any rough estimate of when this could be fixed? thanks

**Comment by aswani521** [comment]
Hey @joamafer thanks for being patient, we are currently testing the new version of the sdk, the fix will go out as part of our next sdk release, which will be early next week. I'll try to see if I can pull it in.

**Comment by johnny-zumper** [comment]
Any update on when the fix will be released? (Thanks @aswani521!)

**Comment by joamafer** [comment]
Thanks for the new version. I'll close this issue now.

**Comment by adamshin** [comment]
@aswani521 We're seeing several similar warnings in our project using version 1.0.2 of the pod. Most of them are iOS 10 deprecation warnings, but there's also issues with nullability specifiers.

> 'UIMutableUserNotificationCategory' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNNotificationCategory
>
> 'UIUserNotificationType' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNAuthorizationOptions
>
> 'UIUserNotificationSettings' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNNotificationSettings
>
> Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)

Our app is built against iOS 13 with a deployment target of iOS 11. Could you look into this again? I'm glad to provide any other information that would be helpful.

**Comment by aswani521** [comment]
hey @adamshin thanks for reporting the issue, we are already working on this issue, i'll keep you posted on the fixes we make.

**Comment by adamshin** [comment]
Any updates on this issue?

**Comment by rahulrvp** [comment]
hello @adamshin we have released a new version of the SDK ([v2.0.1](https://github.com/blueshift-labs/Blueshift-iOS-SDK/releases/tag/2.0.1)) with the warnings addressed. please update.

**Comment by adamshin** [comment]
@rahulrvp We've updated to version 2.0.1. Unfortunately we're still seeing most of the same deprecation warnings.

**Comment by aswani521** [comment]
@adamshin I filed a support request, lets take this over the email I sent you
